import Navigation from "@/components/Navigation";
import Providers from "@/components/Providers"
import '@/styles/global.scss';
export const metadata = {
  title: 'Auxdibible',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"dark:bg-neutral-800 bg-neutral-300"}>
        <Providers>
          <Navigation/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
